_target_: digit_classification.models.cnn.ConvClassifier

conv_blocks_1: 2
conv_blocks_2: 2
hidden_conv_channels: 4
mlp_depth: 3

optimizer_factory:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1.0e-4
