stages:
  - build

build_latest:
  stage: build
  image:
    name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    entrypoint: [""]
  variables:
    TAG: latest
    IMAGE_NAME: docker-image
    DOCKER_FILE: "${CI_PROJECT_DIR}/docker/Dockerfile"
    TO: "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${TAG}"
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${DOCKER_FILE}"
      --destination "${TO}"
