verbose: false
printshellcmds: true
rerun-triggers: mtime
jobs: 10

use-singularity: true
singularity-args: >-
  --nv
  --cleanenv
  --env WANDB_API_KEY=$WANDB_API_KEY
  --bind /srv/beegfs/scratch:/srv/beegfs/scratch

slurm: true
default-resources:
  slurm_account: golling
  slurm_partition: shared-gpu,private-dpnc-gpu
  runtime: 15
  mem_mb: 1000
