_target_: lightning.pytorch.Trainer

min_epochs: null
max_epochs: 2
enable_progress_bar: true
enable_model_summary: true
log_every_n_steps: 1
default_root_dir: null # set by snakemake

callbacks:
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: null
    filename: epoch_{epoch}
    monitor: valid_loss
    mode: min
    save_last: true
    auto_insert_metric_name: false

  model_summary:
    _target_: lightning.pytorch.callbacks.RichModelSummary
    max_depth: 2

  lr_monitor:
    _target_: lightning.pytorch.callbacks.LearningRateMonitor
    logging_interval: step

logger:
  wandb:
    _target_: lightning.pytorch.loggers.wandb.WandbLogger
