config:
  method: bayes
  name: null # gets set by snakemake
  metric:
    goal: minimize
    name: valid_loss
  parameters:
    batch_size:
      values: [512, 1024]
    lr:
      distribution: log_uniform_values
      min: 1e-5
      max: 1e-3
    conv_blocks_1:
      value: 2
    conv_blocks_2:
      value: 2
    hidden_conv_channels:
      value: 8
    mlp_depth:
      value: 3

param_config_keys:
  batch_size: 'datamodule.train_loader_factory.batch_size'
  lr: 'model.optimizer_factory.lr'
  conv_blocks_1: 'model.conv_blocks_1'
  conv_blocks_2: 'model.conv_blocks_2'
  hidden_conv_channels: 'model.hidden_conv_channels'
  mlp_depth: 'model.mlp_depth'

job_count: 1
runs_per_job_count: 1
