_target_: digit_classification.data.mnist.MNISTDataModule
val_frac: 0.1

dev_set_conf:
  load_path: ${io.dataset_path}
  train: true
  size: 10_000

predict_set_conf:
  load_path: ${io.dataset_path}
  train: false
  size: 10_000

dev_loader_conf:
  batch_size: 1024
  num_workers: 3
  pin_memory: true

predict_loader_conf:
  batch_size: 1024
  num_workers: 3
  pin_memory: true
