# output dir will be created by hydra
data_dir: {{ cookiecutter.data_dir }}
output_dir: /home/matthew/Documents/saved_networks
user: {{ cookiecutter.user }}

# Interpolated
root_dir: ${oc.env:PROJECT_ROOT}
full_path: ${paths.output_dir}/${project_name}/${network_name}/
