_target_: digit_classification.plotting.Paper

# emprically determined latex column size (in points)
# dependend on the specific setup used in the paper
columnwidth_pt: 426.79135

# use a standard documentclass; if non standard, find the documentclass
# the non-standard one is based on (these don't do font size definitions from scratch)
latex_documentclass: "scrartcl"
latex_default_fontsize: "12pt"
latex_imports: |
  \usepackage[bitstream-charter]{mathdesign}
  \usepackage[sfdefault]{AlegreyaSans}
  \usepackage{amsmath}
