verbose: false
printshellcmds: true
rerun-triggers: mtime

use-singularity: true
singularity-args: >-
  --nv
  --cleanenv
  --env WANDB_API_KEY=$WANDB_API_KEY
  --env PYTHONPATH=.:libs/mltools
  --bind /srv/beegfs/scratch:/srv/beegfs/scratch

cores: 5
