defaults:
  - _self_

  - load_model: cnn
  - load_datamodule: labelled_digits

  - hydra: default
  - common: default
  - override common: private # create your own and never push! look at default for reference

predictor:
  _target_: lightning.Trainer
  enable_progress_bar: true
  logger: null

io:
  checkpoint_path: train_output/result.ckpt
  predictions_save_path: prediction.npz
