defaults:
  - _self_
  - dataset: mnist
  - model: cnn
  - datamodule: labelled_digits
  - trainer: default
  - wandb: default

model_save_path: null
auto_resume: false

seed: 42
precision: medium
compile: null
