defaults:
  - _self_

  - model: cnn
  - datamodule: mnist

  - trainer: default

  - hydra: default
  - common: default
  - override common: private # create your own and never push! look at default for reference

id: debug # unique identifier for this particular training, useful for logging
seed: 0

# from which checkpoint to start the training; if it doesn't exist, start from scratch (usual case)
init_ckpt_path: "last"

io:
  dataset_path: data.npz
  checkpoints_path: train_output/checkpoints
  result_path: train_output/result.ckpt
  trainer_root: train_output
  logging_dir: train_output
