_target_: model_indep_unfolding.models.flow.InferenceFlow

num_blocks: 5
mlp_width: 64
mlp_depth: 5
bin_count: 10
spline_bound: 5

optimizer_factory:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1.0e-4
