# Enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# This makes hydra overwrite the logging instead of appending
job_logging:
  handlers:
    file:
      mode: w

output_subdir: null
