_target_: lightning.pytorch.Trainer

min_epochs: null
max_epochs: 20
enable_progress_bar: true
enable_model_summary: true
log_every_n_steps: 1
default_root_dir: null # set by snakemake

callbacks:
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: null # gets set by snakemake
    filename: epoch_{epoch}
    monitor: valid_loss
    mode: min
    save_last: true
    auto_insert_metric_name: false

  - _target_: lightning.pytorch.callbacks.RichModelSummary
    max_depth: 2

  - _target_: lightning.pytorch.callbacks.LearningRateMonitor
    logging_interval: step

logger:
  - _target_: lightning.pytorch.loggers.wandb.WandbLogger
