project_name: 'template'
container_path: /srv/beegfs/scratch/users/a/ackersch/projects/template/experiment_env.sif
experiments_base_path: /srv/beegfs/scratch/users/a/ackersch/projects/template/experiments

experiment_group: 'initial_testing'
stage: 'debug'
matmul_precision: medium
model_compile_mode: null

logging:
  wandb_username: jackerschott
