defaults:
  - _self_
  - trainer: default
  - model: cnn
  - dataset: mnist
  - datamodule: labelled_digits
  - wandb: default
  - sweep: non_model_params

stage: 'experiment' # gets set by snakemake

# used for training
seed: 42
precision: medium
compile: null
