_target_: src.{{ cookiecutter.python_package }}.models.generator.UNetDiffusion

min_sigma: 1.0e-5
max_sigma: 80
ema_sync: 0.995
p_mean: -1.2
p_std: 1.2

normaliser_config:
  max_n: 50_000

cosine_config:
  encoding_dim: 16
  scheme: exponential

sampler_function:
  _target_: mltools.mltools.diffusion.sample_heun
  _partial_: True

sigma_function:
  _target_: mltools.mltools.diffusion.get_sigmas_karras
  _partial_: True
  n_steps: 100
  rho: 7

unet_config:
  min_size: 4
  attn_below: 0
  start_channels: 32
  max_channels: 64
  zero_out: True
  n_blocks_per_layer: 1
  resnet_config:
    act: silu
    drp: 0
    nrm_groups: 4
  attn_config:
    num_heads: 4
    nrm_groups: 4
    do_pos_encoding: True

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1.0e-4
  weight_decay: 1.0e-5

sched_config:
  mltools:
    name: warmup
    num_steps: 1000
  lightning:
    monitor: valid/total_loss
    interval: step
    frequency: 1
