verbose: false
printshellcmds: true
jobs: 10
use-singularity: true
singularity-args: >-
  --nv
  --cleanenv
  --env PYTHONPATH=modules

executor: slurm
default-resources:
  slurm_account: golling
  slurm_partition: shared-gpu,private-dpnc-gpu
  runtime: 15
  mem_mb: 1000
